name = "qr-code-app" # You can change this to your preferred app name
main = "src/worker.js"
compatibility_date = "2023-10-30" # Use a recent compatibility date

# Configuration for serving static assets from the 'public' directory
[site]
bucket = "./public"
